1 task 2 solutions
allegro/blog pull request #23
Opened 2021-05-13 09:04 UTC by YevgeniyaLee

1-tasks-2-solutions-spark-or-beam

2021-06-01 14:03 UTC, mkosmul requested changes

2021-06-01 22:12 UTC, YevgeniyaLee reviewed
> Potrzebujemy jeszcze wpisu w _data/members.yml żeby widzieć twoje imię w nagłówku i stopce posta

added https://github.com/allegro/blog/pull/23/commits/3ef80f2e4ea61992cd50642ebe1fa10b298989cd

2021-06-02 05:59 UTC, dopieralad requested changes

2021-06-02 07:31 UTC, wpanas requested changes

2021-06-07 11:49 UTC, mkosmul approved these changes

2021-06-14 07:22 UTC, wpanas requested changes

2021-06-14 20:34 UTC, dopieralad requested changes
Hej @YevgeniyaLee 🙂 
Przeczytałem artykuł raz jeszcze i teraz nie mam już większych uwag oprócz jednego chochlika w obrazku i małej zmiany językowej, do której dodałem automatyczną sugestię :wink:

Wygląda na to, że jak poprawimy te dwie rzeczy oraz potwierdzimy sobie prawidłową responsywność tabelek to będziemy mogli publikować :tada:

Dobra robota 👍

2021-06-15 06:03 UTC, dopieralad approved these changes

2021-06-16 07:37 UTC, wpanas approved these changes

2021-06-28 08:28 UTC, merged