How to ruin es performance part ii no img opt
allegro/blog pull request #35
Opened 2021-08-13 13:25 UTC by mkosmul

2021-09-20 12:02 UTC, krzksz requested changes

2021-09-20 13:36 UTC, krzksz requested changes
Ogólnie bardzo ciekawy i obszerny post. Dobrze się go czyta i nawet nie pracując na co dzień z full-textowymi rozwiązaniami czuję się mądrzejszy o wartościową wiedzę.

2021-10-04 09:39 UTC, dopieralad requested changes

2021-10-04 11:51 UTC, dopieralad approved these changes

2021-10-04 11:54 UTC, krzksz approved these changes

2021-10-05 12:22 UTC, wojtekpon approved these changes
Parę sugestii do poprawki, ogólnie do publikacji

2021-10-07 09:24 UTC, merged