Moving towards Micronaut.
allegro/blog pull request #43
Opened 2021-10-01 07:17 UTC by konrad-kaminski

2021-10-05 13:51 UTC, kzadurska reviewed
Cześć, @konrad-kaminski! Świetne tytuły sekcji 🧡
Kilka sugestii ode mnie:

2021-10-21 13:30 UTC, wojtekpon requested changes

2021-11-02 09:50 UTC, kzadurska reviewed
Jeszcze te dwie literówki się zapodziały

2021-11-04 10:42 UTC, mkosmul requested changes
Fajny post

2021-11-18 10:20 UTC, mkosmul approved these changes

2021-11-18 14:13 UTC, kzadurska approved these changes

2021-11-22 13:10 UTC, merged