time series post
allegro/blog pull request #48
Opened 2021-11-18 17:19 UTC by michalknasiecki

2021-12-09 15:14 UTC, mkosmul requested changes
Fajny tekst, aż sam muszę sprawdzić czy jest potencjał do użycia time series u nas w zespole

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +generated a million queries (it may take some time depending on your hardware, so you can start with a lower amount of
amount -> number (bo queries policzalne)

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +another point goes to time series: simple search is slightly faster than in the case of the regular collection.
another point goes to time series -> time series score another point

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +But we’re yet to discuss the most interesting part. Time series is primarily used for quick aggregate counting. Let’s
is -> are

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +query performance can have on an element that often doesn’t get the adequate attention: proper modelling the data.
proper modelling the data -> proper data modelling

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +It is also not possible to sort by time field, which is another inconvenience. If we want to have
It is also not possible to sort by time field, ... -> It is not possible to sort by time field, either, ...

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +Although these two lacking indexes may seem to be an easy thing to fix, we must remember that it involves additional use
lacking -> missing (lacking brzmi tutaj bardziej jakby indeksom czegoś brakowało a nie brakowało samych indeksów)

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +Adding the ability to store time series in MongoDB is a step in the right direction. First tests show that in a certain
bez "a" przed "certain cases"

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +cases new type of collections really do work better than the regular ones. They use less disc space, are faster at
"the" przed "new type of collection"

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +cases new type of collections really do work better than the regular ones. They use less disc space, are faster at
do -> does

2021-12-09 15:14 UTC, mkosmul commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +working on improving it and will soon eliminate most of the limitations.
"of the" można pominąć

2021-12-10 07:28 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +A few years ago, I was working on a new version of Allegro purchase ratings. It was a time of a pretty large revolution
done

2021-12-10 07:28 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +the concept of purchase rating itself. Replacing the system with positive, neutral or negative rating, we introduced
done

2021-12-10 07:28 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +an approach based on “thumbs up” and “thumbs down” as well as the option to rate several elements of the purchase: the
done

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +migrate data from Oracle to MongoDB. There were many reasons for this decision: from the non-relational nature of our
Bardzo słuszna uwaga, tym bardziej że chwilę później piszę o potrzebie zmniejszenia kosztów, co dodatkowo stawia Oracla w złym świetle. Zmieniłem nazwę na relational database.

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +model, through the need for an easier scaling, to the wish for cost reduction. Upon completion of the works, we were for
done

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +Although these two lacking indexes may seem to be an easy thing to fix, we must remember that it involves additional use
done

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +Adding the ability to store time series in MongoDB is a step in the right direction. First tests show that in a certain
done

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +cases new type of collections really do work better than the regular ones. They use less disc space, are faster at
done

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +cases new type of collections really do work better than the regular ones. They use less disc space, are faster at
done

2021-12-10 07:30 UTC, michalknasiecki commented on _posts/2021-11-18-performance-evaluation-of-timeseries.md
> +working on improving it and will soon eliminate most of the limitations.
done

2021-12-13 08:12 UTC, mkosmul approved these changes

2021-12-20 13:28 UTC, merged